# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed5261d7e9873c1831376a74a8921a61df65ac4f43d47bf83bdff5fd95caeb6bd9d09de79cc53a4788152f1ac8c8a1972bcb4d4e9f72a48be8d9f1d8d1a1d8b0

test:
  secret_key_base: ed818bae9687dfbed852caaf968cece5bc536c8c0a9881c252388e31bf402f4081befae9837bae7f0d6483343cf0f39ba59587ad1e7728f4e4e2fb16eb6e8bda

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
